[package]
name = "omniprompt"
version = "0.1.0"
authors = ["Steven Pease <peasteven@gmail.com>"]
description = "A very customized prompt"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1.2"
nix = "0.22.1"
whoami = "1.1.3"
chrono = "0.4.19"
os_info = "3.0.7"
dirs = "3.0.2"
libc = "0.2.101"
git2 = { version = "0.13.21", default-features = false, optional = true }
sysinfo = "0.20.1"
bytesize = "1.1.0"
target_info = "0.1.0"
anyhow = "1.0.43"

[features]
default = ["git"]
git = ["git2"]
